export const ACTION_REGISTRY = {
  CREATE_LEAD: true,
  UPDATE_LEAD: true,
  DELETE_LEAD: true,
  UPDATE_LEAD_STATUS: true,
  UPDATE_LEAD_OWNER: true,
  ADD_LEAD_ACTIVITY: true,
  CONVERT_LEAD_TO_CUSTOMER: true,

  CREATE_CUSTOMER: true,
  UPDATE_CUSTOMER: true,
  DELETE_CUSTOMER: true,
  CLAIM_CUSTOMER: true,
  RELEASE_CUSTOMER: true,
  AUTO_RETURN_INACTIVE_CUSTOMERS: true,
  ARCHIVE_CUSTOMER: true,
  RESTORE_CUSTOMER: true,
  ADD_CUSTOMER_ACTIVITY: true,

  CREATE_CONTACT: true,
  UPDATE_CONTACT: true,
  DELETE_CONTACT: true,
  SET_PRIMARY_CONTACT: true,
  CREATE_CONTACT_SOCIAL_PROFILE: true,
  DELETE_CONTACT_SOCIAL_PROFILE: true,
  CREATE_CUSTOM_FIELD_DEFINITION: true,
  UPDATE_CUSTOM_FIELD_DEFINITION: true,
  DELETE_CUSTOM_FIELD_DEFINITION: true,
  SET_CUSTOM_FIELD_VALUE: true,

  CREATE_QUOTE: true,
  UPDATE_QUOTE: true,
  DELETE_QUOTE: true,
  UPDATE_QUOTE_STATUS: true,
  RECALCULATE_QUOTE_TOTALS: true,
  CREATE_QUOTE_ITEM: true,
  UPDATE_QUOTE_ITEM: true,
  DELETE_QUOTE_ITEM: true,
  SEND_QUOTE: true,
  ACCEPT_QUOTE: true,
  CONVERT_QUOTE_TO_ORDER: true,
  QUOTE_TO_ORDER: true,

  CREATE_ORDER: true,
  UPDATE_ORDER: true,
  DELETE_ORDER: true,
  UPDATE_ORDER_STATUS: true,
  RECALCULATE_ORDER_TOTALS: true,
  CREATE_ORDER_ITEM: true,
  UPDATE_ORDER_ITEM: true,
  DELETE_ORDER_ITEM: true,

  CREATE_TASK: true,
  UPDATE_TASK: true,
  DELETE_TASK: true,
  COMPLETE_TASK: true,

  CREATE_PROJECT: true,
  UPDATE_PROJECT: true,
  DELETE_PROJECT: true,
  UPDATE_PROJECT_STATUS: true,

  CREATE_PRODUCT: true,
  UPDATE_PRODUCT: true,
  DELETE_PRODUCT: true,

  CREATE_FOLLOW_UP: true,
  UPDATE_FOLLOW_UP: true,
  DELETE_FOLLOW_UP: true,

  CREATE_TEMPLATE: true,
  UPDATE_TEMPLATE: true,
  DELETE_TEMPLATE: true,

  CREATE_CALENDAR_EVENT: true,
  UPDATE_CALENDAR_EVENT: true,
  DELETE_CALENDAR_EVENT: true,
  COMPLETE_CALENDAR_EVENT: true,

  CREATE_DOCUMENT: true,
  UPDATE_DOCUMENT: true,
  DELETE_DOCUMENT: true,

  CREATE_BUSINESS_LINE: true,
  UPDATE_BUSINESS_LINE: true,
  DELETE_BUSINESS_LINE: true,

  UPSERT_SALES_GOAL: true,
  UPDATE_SALES_GOAL: true,

  CREATE_CUSTOMER_LIST_VIEW: true,
  UPDATE_CUSTOMER_LIST_VIEW: true,
  DELETE_CUSTOMER_LIST_VIEW: true,
  DUPLICATE_CUSTOMER_LIST_VIEW: true,
  SET_DEFAULT_CUSTOMER_LIST_VIEW: true,
  CREATE_ORDER_LIST_VIEW: true,
  UPDATE_ORDER_LIST_VIEW: true,
  DELETE_ORDER_LIST_VIEW: true,
  SET_DEFAULT_ORDER_LIST_VIEW: true,

  CREATE_EXTERNAL_SOURCE: true,
  UPDATE_EXTERNAL_SOURCE: true,
  DELETE_EXTERNAL_SOURCE: true,
  TOGGLE_EXTERNAL_SOURCE_ACTIVE: true,
  REGENERATE_EXTERNAL_SOURCE_API_KEY: true,

  CREATE_INVOICE: true,
  UPDATE_INVOICE: true,
  DELETE_INVOICE: true,
  RECORD_PAYMENT: true,

  DELETE_AI_ANALYSIS: true,
  AI_ACTION: true,
} as const;

export type RegisteredActionType = keyof typeof ACTION_REGISTRY;

export function assertRegisteredAction(actionType: string): asserts actionType is RegisteredActionType {
  if (!Object.prototype.hasOwnProperty.call(ACTION_REGISTRY, actionType)) {
    throw new Error(`[KERNEL_UNKNOWN_ACTION] ${actionType}`);
  }
}
